[backend]

[backend.store]
dir = "store/kv_test"
sync_every_write = true
index_type = "Skiplist"

[backend.file]
max_file_size = 4096

[backend.batched]
max_batch_size = 128
sync_every_write = true


[directory]
depth = 4
